# CanJumpToASubroutineAndJumpBackAgain
# JSRDoesNotAffectTheProcessorStatus
# RTSDoesNotAffectTheProcessorStatus
# JumpAbsoluteCanJumpToAnNewLocationInTheProgram
# JumpIndirectCanJumpToAnNewLocationInTheProgram
